backend:
  name: git-gateway
  repo: adamdjbrett/jcrt.org
  branch: main
#  base_url: https://jcrt-auth.adam.workers.dev
#  auth_endpoint: auth
#  local_backend: true

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "home"
    label: "Home"
    editor:
      preview: false
    files:
      - file: "content/index.md"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text" ,required: false}
          - {label: "Image", name: "image", widget: "image",required: false}
          - {label: "Hero Text", name: "text", widget: "text", hint: "The main text under the hero image.",required: false}
          - label: "Hero Button"
            name: "button"
            widget: "object"
            required: false
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - label: "Featured Section"
            name: "section"
            widget: "object"
            required: false
            fields:
              - {label: "Section Title", name: "title", widget: "string"}
              - {label: "Mode", name: "mode", widget: "string"}
          - label: "Blog Section"
            name: "blog"
            widget: "object"
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}

  - name: "blogIndex"
    label: "Blog Index"
    editor:
      preview: false
    files:
      - file: "content/blog.md"
        label: "Blog Listing Page"
        name: "blog_index"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text" , required: false  }
          - label: "Pagination Settings"
            name: "pagination"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Page Size", name: "size", widget: "number", value_type: "int", default: 6}
              - {label: "Reverse Order", name: "reverse", widget: "boolean", default: true}
          - {label: "Body Content (Optional)", name: "body", widget: "markdown", required: false}

  - name: "authors_profile"
    label: "Author Profiles"
    folder: "content/authors"
    create: true
    identifier_field: "name"
    editor:
      preview: false
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string", hint: "Author Name."}
      - {label: "Affiliation", name: "affiliation", widget: "string", hint: "Affiliation.",required: false}
      - {label: "Biography", name: "bio", widget: "text", hint: "Bio." ,required: false}
      - label: "Social Links"
        name: "social"
        widget: "list"
        required: false
        collapsed: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Icon (Font Awesome)", name: "icon", widget: "string", hint: "e.g., fa-solid fa-envelope"}
          - {label: "URL", name: "url", widget: "string",required: false}

  - name: "posts"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", hint: "A short summary of the post.", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime",required: false}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"} , required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown",required: false}


  - name: "pages"
    label: "Static Pages"
    folder: "content/pages"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text",required: false}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "Example: /about/",required: false}
      - {label: "Body", name: "body", widget: "markdown",required: false}
  - name: "archives"
    label: "Archives"
    folder: "content/archives"
    create: true
    editor:
      preview: false
    extension: "md"
    format: "frontmatter"
    nested: { depth: 5 }
    summary: "{{fields.volume}}.{{fields.issue}} | {{fields.title}}"
    path: "{{fields.volume}}.{{fields.issue}}/{{slug}}"
    view_groups:
      - label: "Volume"
        field: "volume"
      - label: "Issue"
        field: "issue"
    sortable_fields: ["volume", "issue", "article_number"]
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "archives.njk"}
      - {label: "Article Number", name: "article_number", widget: "string", hint: "Use 01, 02,"}
      - {label: "Volume", name: "volume", widget: "string", hint: "Eg: 24"}
      - {label: "Issue", name: "issue", widget: "string", hint: "Eg: 1"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Affiliation", name: "affiliation", widget: "string", hint: "Affiliation" ,required: false}
      - {label: "Abstract", name: "abstract", widget: "text", required: false}
      - {label: "PDF File", name: "pdf", widget: "file", hint: "PDF file",required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "metadata"
    label: "Metadata"
    editor:
      preview: false
    files:
      - file: "_data/metadata.yaml"
        label: "Site Metadata"
        name: "site_metadata"
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description", name: "description", widget: "text"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Language", name: "language", widget: "string"}
        - {label: "Locale", name: "locale", widget: "string"}
        - {label: "Favicon", name: "favicon", widget: "image"}
        - {label: "URL", name: "url", widget: "string"}
        - label: "Metasocial"
          name: "metasocial"
          widget: "list"
          fields:
            - {label: "Facebook", name: "facebook", widget: "string", required: false}
            - {label: "Twitter User", name: "twitteruser", widget: "string", required: false}
            - {label: "Twitter", name: "twitter", widget: "string", required: false}
        - label: "Navbar"
          name: "navbar"
          widget: "object"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Sub Title", name: "sub_title", widget: "string"}
            - label: "Social Links"
              name: "social"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Icon (Font Awesome)", name: "icon", widget: "string"}
                - {label: "URL", name: "url", widget: "string"}
        - label: "Sidebar"
          name: "sidebar"
          widget: "object"
          fields:
            - label: "Menu"
              name: "menu"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - label: "List Menu"
                  name: "list"
                  widget: "list"
                  fields:
                    - {label: "Nav Text", name: "nav", widget: "string"}
                    - {label: "URL", name: "url", widget: "string"}
            - label: "Info Section"
              name: "info"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - label: "List Items"
                  name: "list"
                  widget: "list"
                  fields:
                    - {label: "Image", name: "image", widget: "image"}
                    - {label: "Text", name: "text", widget: "text"}
                    - {label: "URL", name: "url", widget: "string"}
                - label: "Button"
                  name: "button"
                  widget: "object"
                  fields:
                    - {label: "Text", name: "text", widget: "string"}
                    - {label: "URL", name: "url", widget: "string"}
            - label: "Contact"
              name: "contact"
              widget: "object"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Text", name: "text", widget: "text"}
                - label: "Contact List"
                  name: "list"
                  widget: "list"
                  fields:
                    - {label: "Title", name: "title", widget: "string"}
                    - {label: "Icon (Font Awesome)", name: "icon", widget: "string"}
                    - {label: "URL", name: "url", widget: "string"}
        - label: "Footer"
          name: "footer"
          widget: "object"
          fields:
            - {label: "Text", name: "text", widget: "string"}
            
        - label: "Theory Dir"
          name: "site"
          widget: "object"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "text"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "Authors", name: "authors", widget: "string"}
            - {label: "Alert", name: "alert", widget: "markdown"}
        - {label: "Github User API Religious Theory", name: "github_user", widget: "string"}
        - {label: "Github Repo API Religious Theory", name: "github_repo", widget: "string"}
        - {label: "Github Branch API Religious Theory", name: "branch", widget: "string"}
